KISSY.add("gallery/slide/1.0/base",function(S){"use strict";var $=S.Node.all;var BSlide=function(){if(!(this instanceof BSlide)){throw new Error('please use "new Slide()"');}
this.init.apply(this,arguments);};BSlide.plug=function(fn){};S.augment(BSlide,S.Event.Target,{init:function(selector,config){var self=this;if(S.isObject(selector)){self.con=selector;}else if(/^#/i.test(selector)){self.con=S.one(selector);}else if(S.one("#"+selector)){self.con=S.one("#"+selector);}else if(S.one(selector)){self.con=S.one(selector);}else{throw new Error('Slide Container Hooker not found');}
self.buildParam(config);self.buildHTML();self.bindEvent();self.fire('ready',{index:0,navnode:self.tabs.item(0),pannelnode:self.pannels.item(0)});if(self.reverse){var _t;_t=self.previous;self.previous=self.next;self.next=_t;}
if(self.carousel){for(var i=0;i<self.colspan;i++){self.fix_for_transition_when_carousel(i*2);}}
self.fixSlideSize();if(self.layerSlide){self.initLayer();}
return this;},setWrapperSize:function(offset){var self=this;if(S.isUndefined(offset)){offset=0;}
self.pannels=self.con.all('.'+self.contentClass+' div.'+self.pannelClass);self.length=self.pannels.length;var reHandleSize={'none':function(){},'vSlide':function(){var animconRegion=self.animcon.get('region');self.animwrap.setStyles({'height':(self.length+offset)*animconRegion.height/self.colspan+'px'});},'hSlide':function(){var animconRegion=self.animcon.get('region');self.animwrap.setStyles({'width':(self.length+offset)*animconRegion.width/self.colspan+'px'});},'fade':function(){}};reHandleSize[self.effect]();if(!S.isUndefined(offset)){self.relocateCurrentTab();}
return this;},add:function(node,index){var self=this;if(S.isUndefined(index)||index>self.length){index=self.length;}
if(S.isString(node)){node=S.one(node);}
if(self.transitions){node.css({visibility:'hidden'});}
if(index==self.length){setTimeout(function(){self.setWrapperSize(1);},0);node.insertAfter(self.pannels[index-1]);}else{node.insertBefore(self.pannels[index]);}
self.setWrapperSize();self.fixSlideSize(self.currentTab);if(self.transitions){node.css({visibility:''});}
if(self.transitions){}
return this;},remove:function(index){var self=this;if(self.length===1){return;}
if(index<=self.currentTab){self.currentTab--;self.length--;}
if(self.transitions){self.con.css({display:'none'});}
S.one(self.pannels[index]).remove();self.setWrapperSize();if(self.transitions){self.con.css({display:'block'});}
self.fixSlideSize(self.currentTab);return this;},removeLast:function(){var self=this;self.remove(self.length-1);return self;},renderLazyData:function(textarea){var self=this;textarea.setStyle('display','none');if(textarea.attr('lazy-data')=='1'){return;}
textarea.attr('lazy-data','1');var id=S.stamp(div),html=textarea.get('innerHTML').replace(/&lt;/ig,'<').replace(/&gt;/ig,'>'),div=S.Node.create('<div>'+html+'</div>');S.DOM.insertBefore(div,textarea);S.execScript(html);},buildWrap:function(){var self=this;self.animwrap=S.Node.create('<div style="position:absolute;"></div>');self.animwrap.set('innerHTML',self.animcon.get('innerHTML'));self.animcon.set('innerHTML','');self.animcon.appendChild(self.animwrap);self.pannels=self.con.all('.'+self.contentClass+' div.'+self.pannelClass);return self;},doEffectInit:function(){var self=this;var effectInitFn={'none':function(){self.pannels=self.con.all('.'+self.contentClass+' div.'+self.pannelClass);self.pannels.setStyles({display:'none'});self.pannels.item(self.defaultTab).setStyles({'display':'block'});},'vSlide':function(){self.buildWrap();var animconRegion=self.animcon.get('region');self.pannels.setStyles({'float':'none','overflow':'hidden'});self.animwrap.setStyles({'height':self.length*animconRegion.height/self.colspan+'px','overflow':'hidden','top':-1*self.defaultTab*animconRegion.height+'px'});},'hSlide':function(){self.buildWrap();var animconRegion=self.animcon.get('region');self.pannels.setStyles({'float':'left','overflow':'hidden'});self.animwrap.setStyles({'width':self.length*animconRegion.width/self.colspan+'px','overflow':'hidden','left':-1*self.defaultTab*animconRegion.width+'px'});},'fade':function(){self.pannels=self.con.all('.'+self.contentClass+' div.'+self.pannelClass);self.pannels.setStyles({'position':'absolute','zIndex':0});self.pannels.each(function(node,i){if(i==self.defaultTab){node.setStyles({'opacity':1,'display':'block'});}else{node.setStyles({'opacity':0,'diaplay':'none'});}});}};effectInitFn[self.effect]();return this;},buildHTML:function(){var self=this;var con=self.con;self.tabs=con.all('.'+self.navClass+' '+self.triggerSelector);var tmp_pannels=con.all('.'+self.contentClass+' .'+self.pannelClass);self.length=tmp_pannels.size();if(!con.one('.'+self.navClass)){S.Node('<ul class="'+self.navClass+'" style="display:none"></ul>').appendTo(self.con);}
if(self.tabs.size()===0){var t_con=con.all('.'+self.navClass);var t_str='';for(var i=0;i<self.length;i++){var t_str_prefix='';if(i===0){t_str_prefix=self.selectedClass;}
t_str+='<li class="'+t_str_prefix+'"><a href="javascript:void(0);">'+(i+1)+'</a></li>';}
t_con.set('innerHTML',t_str);}
self.tabs=con.all('.'+self.navClass+' '+self.triggerSelector);self.animcon=con.one('.'+self.contentClass);self.animwrap=null;self.doEffectInit();self.fixSlideSize(self.currentTab);self.hightlightNav(self.getWrappedIndex(self.currentTab));if(self.autoSlide===true){self.play();}
return this;},getCurrentPannel:function(){var self=this;return S.one(self.pannels[self.currentTab]);},renderWidth:function(){var self=this;var width=self.animcon.get('region').width;if(self.effect=='hSlide'){width/=self.colspan;}
self.pannels.setStyles({width:width+'px'});return this;},renderHeight:function(){var self=this;var height=self.animcon.get('region').height;if(self.effect=='vSlide'){height/=self.colspan;}
self.pannels.setStyles({height:height+'px'});return this;},relocateCurrentTab:function(index){var self=this;if(S.isUndefined(index)){index=self.currentTab;}
if(self.effect!='hSlide'){return;}
if(self.transitions){self.animwrap.setStyles({'-webkit-transition-duration':'0s','-webkit-transform':'translate3d('+(-1*index*self.animcon.get('region').width)+'px,0,0)','-webkit-backface-visibility':'hidden'});}else{self.animwrap.setStyles({left:-1*index*self.animcon.get('region').width});}
self.currentTab=index;return this;},fixSlideSize:function(index){var self=this;if(self.adaptive_fixed_width){self.renderWidth();}
if(self.adaptive_fixed_height){self.renderHeight();}
if(self.adaptive_fixed_size){self.renderHeight().renderWidth();}
self.resetSlideSize(index);return this;},removeHeightTimmer:function(){var self=this;if(!S.isNull(self.heightTimmer)){clearInterval(self.heightTimmer);self.heightTimmer=null;}},addHeightTimmer:function(){var self=this;if(!S.isNull(self.heightTimmer)){clearInterval(self.heightTimmer);self.heightTimmer=null;}
var resetHeight=function(){if(self.effect=='hSlide'){self.animcon.setStyles({height:self.pannels.item(self.currentTab).get('region').height+'px'});}};self.heightTimmer=setInterval(resetHeight,100);resetHeight();},resetSlideSize:function(index){var self=this;var width,height;if(typeof index=='undefined'||index===null){index=self.currentTab;}
if(self.effect!='hSlide'&&self.effect!='vSlide'){return;}
if(self.effect=='hSlide'){width=self.adaptive_width?self.adaptive_width():self.animcon.get('region').width;height=self.pannels.item(index).get('region').height;width/=self.colspan;self.pannels.setStyles({width:width+'px',display:'block'});self.animcon.setStyles({width:width*self.colspan+'px',overflow:'hidden'});if(self.animWrapperAutoHeightSetting){self.animcon.setStyles({height:height+'px'});}}
if(self.effect=='vSlide'){width=self.pannels.item(index).get('region').width;height=self.adaptive_height?self.adaptive_height():self.animcon.get('region').height;height/=self.colspan;self.pannels.setStyles({height:height*self.colspan+'px',display:'block'});self.animcon.setStyles({height:height*self.colspan+'px',overflow:'hidden'});if(self.animWrapperAutoHeightSetting){self.animcon.setStyles({width:width+'px'});}}
return this;},getWrappedIndex:function(index){var self=this,wrappedIndex=0;if(index===0){}
if(self.carousel){if(index<self.colspan){wrappedIndex=self.length-self.colspan*3+index;}else if(index>=self.length-self.colspan){wrappedIndex=index-(self.length-self.colspan);}else{wrappedIndex=index-self.colspan;}}else{wrappedIndex=index;}
return wrappedIndex;},bindEvent:function(){var self=this;if(S.inArray(self.eventType,['click','mouseover','mouseenter'])){self.con._delegate(self.eventType,function(e){e.halt();var ti=Number(self.tabs.indexOf(e.currentTarget));if(self.carousel){ti=(ti+1)%self.length;}
self.go(ti);if(self.autoSlide){self.stop().play();}},'.'+self.navClass+' '+self.triggerSelector);}
if(self.hoverStop){self.con._delegate('mouseover',function(e){if(self.autoSlide)self.stop();},'.'+self.contentClass+' div.'+self.pannelClass);self.con._delegate('mouseout',function(e){if(self.autoSlide)self.play();},'.'+self.contentClass+' div.'+self.pannelClass);}
S.Event.on(window,'resize',function(e){self.fixSlideSize(self.currentTab);self.relocateCurrentTab();});self.on('beforeSwitch',function(o){if(this.layerSlide&&this.isAming()){return false;}});if('ontouchstart'in document.documentElement){if(!self.touchmove){return this;}
self.con._delegate('touchstart',function(e){self.stop();self.touching=true;if(self.is_last()&&self.carousel){self.fix_next_carousel();}
if(self.is_first()&&self.carousel){self.fix_pre_carousel();}
self.startX=e.changedTouches[0].clientX;self.startY=e.changedTouches[0].clientY;self.animwrap.setStyles({'-webkit-transition-duration':'0s'});self.startT=Number(new Date());},'.'+self.contentClass);self.con._delegate('touchend',function(e){self.touching=false;var endX=e.changedTouches[0].clientX;var width=Number(self.animcon.get('region').width);self.deltaX=Math.abs(endX-self.startX);var swipeleft=(Math.abs(endX)<Math.abs(self.startX));var swiperight=!swipeleft;var anti=self.carousel?false:(self.is_last()&&swipeleft||self.is_first()&&swiperight);var reset=function(){self.animwrap.setStyles({'-webkit-transition-duration':(Number(self.speed)/2)+'s','-webkit-transform':'translate3d('+(-1*self.currentTab*self.animcon.get('region').width/self.colspan)+'px,0,0)'});};var goswipe=function(){var colwidth=self.animcon.get('region').width/self.colspan;var span=parseInt((self.deltaX-colwidth/2)/colwidth,10);if(swipeleft){if(span>=1&&self.length>2){self.currentTab+=span;if(self.currentTab>=self.length-1){self.currentTab=self.length-2;}}
self.next();}else{if(span>=1&&self.length>2){if(self.currentTab-span<=0){self.currentTab=1;}else{self.currentTab+=-1*span;}}
self.previous();}};if(self.touchmove&&self.deltaX<30){reset();return;}
if(!anti&&((self.touchmove&&(self.deltaX>width/3))||(!self.touchmove&&self.carousel)||(!self.carousel&&self.touchmove&&self.effect=='hSlide')||(!self.touchmove&&!self.carousel)||(Number(new Date())-self.startT<550))){goswipe();}else{reset();}
if(self.autoSlide){self.play();}},'.'+self.contentClass);if(self.touchmove){self.con._delegate('touchmove',function(e){if(e.touches.length>1)return;self.deltaX=e.touches[0].clientX-self.startX;var anti=(self.is_last()&&self.deltaX<0||self.is_first()&&self.deltaX>0);if(!self.carousel&&self.effect=='hSlide'&&anti){self.deltaX=self.deltaX/3;}
self.isScrolling=(Math.abs(self.deltaX)<Math.abs(e.touches[0].clientY-self.startY))?true:false;if(!self.isScrolling){e.halt();self.stop();var width=Number(self.animcon.get('region').width/self.colspan);var dic=self.deltaX-self.currentTab*width;self.animwrap.setStyles({'-webkit-transition-duration':'0s','-webkit-transform':'translate3d('+dic+'px,0,0)'});}},'.'+self.contentClass);self.animwrap.on('webkitTransitionEnd',function(){});}}
return this;},initLayer:function(){var self=this;if('ontouchstart'in document.documentElement){return;}
if(S.UA.ie>0&&S.UA.ie<9){return;}
var SubLayerString=["durationin","easingin","durationout","easingout","delayin","delayout","slideindirection","slideoutdirection","offsetin","offsetout","alpha","easeInStrong","easeOutStrong","easeBothStrong","easeNone","easeIn","easeOut","easeBoth","elasticIn","elasticOut","elasticBoth","backIn","backOut","backBoth","bounceIn","bounceOut","bounceBoth","left","top","right","bottom"];var SubLayerConfig={"durationin":1000,"easingin":'easeIn',"durationout":1000,"easingout":'easeOut',"delayin":300,"delayout":300,"slideindirection":'right',"slideoutdirection":'left',"alpha":true,"offsetin":50,"offsetout":50};var SubLayer=function(el){var that=this;var _sublayer_keys=[];var json=el.attr('rel').replace(/"'/ig,'').replace(new RegExp('('+SubLayerString.join('|')+')',"ig"),'"$1"');var o=S.JSON.parse('{'+json+'}');function setParam(def,key){var v=o[key];that[key]=(v===undefined||v===null)?def:v;}
S.each(SubLayerConfig,setParam);this.el=el;this.left=Number(el.css('left').replace('px',''));this.top=Number(el.css('top').replace('px',''));this.animIn=function(){var that=this;var offsetIn=that.offsetin;var inType=that.slideindirection;var prepareEl={left:function(){that.el.css({'left':that.left-offsetIn});},top:function(){that.el.css({'top':that.top-offsetIn});},right:function(){that.el.css({'left':that.left+offsetIn});},bottom:function(){that.el.css({'top':that.top+offsetIn});}};prepareEl[inType]();setTimeout(function(){var SlideInEffectTo={left:{left:that.left},top:{top:that.top},bottom:{top:that.top},right:{left:that.left}};var to={};S.mix(to,SlideInEffectTo[inType]);if(that.alpha){S.mix(to,{opacity:1});}
S.Anim(that.el,to,that.durationin/1000,that.easingin,function(){}).run();},that.delayin);if(that.alpha){that.el.css({opacity:0});}};this.animOut=function(){};};self.sublayers=[];self.pannels.each(function(node,index){if(self.effect=='vSlide'||self.effect=='hSlide'){node.css({position:'relative'});}
if(node.all('[alt="sublayer"]').length===0){self.sublayers[index]=[];return;}
if(self.sublayers[index]===undefined){self.sublayers[index]=[];}
node.all('[alt="sublayer"]').each(function(el,j){self.sublayers[index].push(new SubLayer(el));});});self.on('beforeSwitch',function(o){if(o.index===self.currentTab){return false;}
self.subLayerRunin(o.index);});self.on('beforeTailSwitch',function(o){self.subLayerRunout(o.index);});},subLayerRunin:function(index){var self=this;var a=self.sublayers[index];S.each(a,function(o,i){o.animIn();});},subLayerRunout:function(index){var self=this;var a=self.sublayers[index];S.each(a,function(o,i){o.animOut();});},buildParam:function(o){var self=this;if(o===undefined||o===null){o={};}
function setParam(def,key){var v=o[key];self[key]=(v===undefined||v===null)?def:v;}
S.each({autoSlide:false,speed:500,timeout:3000,effect:'none',eventType:'click',easing:'easeBoth',hoverStop:true,selectedClass:'selected',conClass:'t-slide',navClass:'tab-nav',triggerSelector:'li',contentClass:'tab-content',pannelClass:'tab-pannel',carousel:false,reverse:false,touchmove:false,adaptive_fixed_width:false,adaptive_fixed_height:false,adaptive_fixed_size:false,adaptive_width:false,adaptive_height:false,defaultTab:0,layerSlide:false,layerClass:'tab-animlayer',colspan:1,animWrapperAutoHeightSetting:true,webkitOptimize:true},setParam);S.mix(self,{tabs:[],animcon:null,pannels:[],timmer:null,touching:false});self.speed=self.speed/1000;if(self.defaultTab!==0){self.defaultTab=Number(self.defaultTab)-1;}
if(self.carousel){self.defaultTab=self.colspan;self.effect='hSlide';}
self.currentTab=self.defaultTab;self.transitions=("webkitTransition"in document.body.style&&self.webkitOptimize);return self;},fix_for_transition_when_carousel:function(index){var self=this;if(typeof index=='undefined'){index=0;}
var con=self.con;self.animcon=self.con.one('.'+self.contentClass);self.animwrap=self.animcon.one('div');self.pannels=con.all('.'+self.contentClass+' div.'+self.pannelClass);if(self.effect=='hSlide'){var width=Number(self.animcon.get('region').width/self.colspan);var height=Number(self.animcon.get('region').height);self.animwrap.setStyle('width',self.pannels.size()*width+2*width);var first=self.pannels.item(index).cloneNode(true);var last=self.pannels.item(self.pannels.size()-1-index).cloneNode(true);self.animwrap.append(first);self.animwrap.prepend(last);if(self.transitions){self.animwrap.setStyles({'-webkit-transition-duration':'0s','-webkit-transform':'translate3d('+(-1*width*(index/2+1))+'px,0,0)','-webkit-backface-visibility':'hidden','left':'0'});}else{self.animwrap.setStyle('left',-1*width*(index/2+1));}}
self.pannels=con.all('.'+self.contentClass+' div.'+self.pannelClass);self.length=self.pannels.size();return this;},isAming:function(){var self=this;if(self.anim){return self.anim.isRunning();}else{return false;}},previous:function(callback){var self=this;try{if(self.isAming()&&self.carousel){return this;}}catch(e){}
var _index=self.currentTab+self.length-1-(self.colspan-1);if(_index>=(self.length-self.colspan+1)){_index=_index%(self.length-self.colspan+1);}
if(self.carousel){if(self.is_first()){self.fix_pre_carousel();self.previous.call(self);return this;}}
self.go(_index,callback);return this;},is_last:function(){var self=this;if(self.currentTab==(self.length-(self.colspan-1)-1)){return true;}else{return false;}},is_first:function(){var self=this;if(self.currentTab===0){return true;}else{return false;}},next:function(callback){var self=this;try{if(self.isAming()&&self.carousel){return this;}}catch(e){}
var _index=self.currentTab+1;if(_index>=(self.length-self.colspan+1)){_index=_index%(self.length-self.colspan+1);}
if(self.carousel){if(self.is_last()){self.fix_next_carousel();self.next.call(self);return this;}}
self.go(_index,callback);return this;},fix_next_carousel:function(){var self=this;self.currentTab=self.colspan;var con=self.con;if(self.effect!='none'){self.pannels=con.all('.'+self.contentClass+' div.'+self.pannelClass);}
var dic='-'+Number(self.animcon.get('region').width).toString()+'px';if(self.effect=='hSlide'){if(self.transitions){self.animwrap.setStyles({'-webkit-transition-duration':'0s','-webkit-transform':'translate3d('+dic+',0,0)'});}else{self.animwrap.setStyle('left',dic);}}else if(self.effect=='vSlide'){}
return;},fix_pre_carousel:function(){var self=this;self.currentTab=self.length-1-self.colspan*2+1;var con=self.con;if(self.effect!='none'){self.pannels=con.all('.'+self.contentClass+' div.'+self.pannelClass);}
var dic='-'+(Number(self.animcon.get('region').width/self.colspan)*(self.currentTab)).toString()+'px';if(self.effect=='hSlide'){if(self.transitions){self.animwrap.setStyles({'-webkit-transition-duration':'0s','-webkit-transform':'translate3d('+dic+',0,0)'});}else{self.animwrap.setStyle('left',dic);}}else if(self.effect=='vSlide'){}
return;},hightlightNav:function(index){var self=this;if(self.carousel&&self.colspan>1){return this;}
if(self.tabs.item(index)){self.tabs.removeClass(self.selectedClass);self.tabs.item(index).addClass(self.selectedClass);}
return this;},switch_to:function(index,callback){var self=this;var afterSwitch=function(){if(S.isFunction(callback)){callback.call(self,self);}
self.fire('afterSwitch',{index:self.currentTab,navnode:self.tabs.item(self.getWrappedIndex(self.currentTab)),pannelnode:self.pannels.item(self.currentTab)});};self.fire('beforeTailSwitch',{index:self.currentTab,navnode:self.tabs.item(self.getWrappedIndex(self.currentTab)),pannelnode:self.pannels.item(self.currentTab)});self.hightlightNav(self.getWrappedIndex(index));self.fixSlideSize(index);if(self.autoSlide){self.stop().play();}
if(index>=self.length){index=index%self.length;}
if(index==self.currentTab){return this;}
if(self.anim){try{self.anim.stop();self.anim=null;}catch(e){}}
var animFn={'none':function(index){self.pannels.setStyles({'display':'none'});self.pannels.item(index).setStyles({'display':'block'});afterSwitch();},'vSlide':function(index){if(self.transitions){self.animwrap.setStyles({'-webkit-transition-duration':self.speed+'s','-webkit-transform':'translate3d(0,'+(-1*index*self.animcon.get('region').height/self.colspan)+'px,0)','-webkit-backface-visibility':'hidden'});self.anim=S.Anim(self.animwrap,{opacity:1},self.speed,self.easing,function(){afterSwitch();});self.anim.run();}else{self.anim=S.Anim(self.animwrap,{top:-1*index*self.animcon.get('region').height/self.colspan},self.speed,self.easing,function(){afterSwitch();});self.anim.run();}},'hSlide':function(index){if(self.transitions){self.animwrap.setStyles({'-webkit-transition-duration':self.speed+'s','-webkit-transform':'translate3d('+(-1*index*self.animcon.get('region').width/self.colspan)+'px,0,0)','-webkit-backface-visibility':'hidden'});self.anim=S.Anim(self.animwrap,{opacity:1},self.speed,self.easing,function(){afterSwitch();});self.anim.run();}else{self.anim=S.Anim(self.animwrap,{left:-1*index*self.animcon.get('region').width/self.colspan},self.speed,self.easing,function(){afterSwitch();});self.anim.run();}},'fade':function(index){var _curr=self.currentTab;self.anim=S.Anim(self.pannels.item(index),{opacity:1},self.speed,self.easing,function(){self.pannels.item(_curr).setStyle('zIndex',0);self.pannels.item(index).setStyle('zIndex',1);self.pannels.item(_curr).setStyle('opacity',0);self.pannels.item(_curr).setStyles({'display':'none'});afterSwitch();});self.pannels.item(index).setStyles({'display':'block'});self.pannels.item(index).setStyle('opacity',0);self.pannels.item(_curr).setStyle('zIndex',1);self.pannels.item(index).setStyle('zIndex',2);self.anim.run();}};animFn[self.effect](index);self.currentTab=index;self.fire('switch',{index:index,navnode:self.tabs.item(self.getWrappedIndex(index)),pannelnode:self.pannels.item(index)});var scriptsArea=self.pannels.item(index).all('.data-lazyload');if(scriptsArea){scriptsArea.each(function(node,i){self.renderLazyData(node);});}},"go":function(index,callback){var self=this;var goon=self.fire('beforeSwitch',{index:index,navnode:self.tabs.item(index),pannelnode:self.pannels.item(index)});if(goon!==false){if(index+self.colspan>self.pannels.size()){index=self.pannels.size()-self.colspan;}
self.switch_to(index,callback);}
return this;},play:function(){var self=this;if(self.timer!==null){clearTimeout(self.timer);}
self.timer=setTimeout(function(){self.next().play();},Number(self.timeout));return this;},stop:function(){var self=this;clearTimeout(self.timer);self.timer=null;return this;}});return BSlide;},{requires:['node','event','json','./slide-util','./kissy2yui']});KISSY.add("gallery/slide/1.0/index",function(S,BSlide){return BSlide;},{requires:['./base']});KISSY.add('gallery/slide/1.0/kissy2yui',function(S){"use strict";S.augment(S.Node,{_delegate:function(){var self=this;if(S.isFunction(arguments[1])){self.delegate(arguments[0],arguments[2],arguments[1]);}else{self.delegate.apply(self,arguments);}
return self;},indexOf:function(node){var self=this;if(S.isUndefined(node)){return null;}
if(node[0]){node=node[0];}
var i=0;self.each(function(el,index){if(el[0]===node){i=index;}});return i;},size:function(){return this.length;},set:function(k,v){if(k==='innerHTML'){this.html(v);}else{this.attr(k,v);}
return this;},get:function(k){var self=this;var o={'innerHTML':function(){return self.html();},'region':function(){return{'height':self.height(),'width':self.width()};}};if(k in o){return o[k]();}},appendChild:function(){this.append.apply(this,arguments);return this;},setStyle:function(k,v){this.css.apply(this,arguments);return this;},setStyles:function(o){this.css.apply(this,arguments);return this;},cloneNode:function(){return this.clone.apply(this,arguments);}});S.Node.create=function(str){return S.Node(str);};},{requires:['node','event']});KISSY.add('gallery/slide/1.0/slide-util',function(S){"use strict";S.mix(S,{setHash:function(sUrl,data){var url;var i;if(typeof sUrl=='object'){url=window.location.href;data=sUrl;}else{url=sUrl;}
if(url.indexOf("#")<0){url+='#';}
var o=this.getHash(url);for(i in data){o[i]=data[i];}
url=url.split("#")[0]+'#';for(i in o){url+=i+'='+o[i]+'&';}
url=url.substr(0,url.length-1);return url;},getHash:function(sUrl){var url=sUrl||window.location.href;if(url.indexOf("#")<0){return{};}else{var hash=url.split('#')[1];if(hash==='')return{};if(hash[hash.length-1]=='&')hash=hash.substr(0,hash.length-1);hash=hash.replace(/"/ig,'\'');hash=hash.replace(/=/ig,'":"');hash=hash.replace(/&/ig,'","');hash+='"';hash="{\""+hash+"}";var o=S.JSON.parse(hash);return o;}},_globalEval:function(data){if(data&&/\S/.test(data)){var head=document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0],script=document.createElement('script');script.text=data;head.insertBefore(script,head.firstChild);setTimeout(function(){head.removeChild(script);},1);}},execScript:function(html){var self=this;var re_script=new RegExp(/<script([^>]*)>([^<]*(?:(?!<\/script>)<[^<]*)*)<\/script>/ig);var hd=S.one('head').getDOMNode(),match,attrs,srcMatch,charsetMatch,t,s,text,RE_SCRIPT_SRC=/\ssrc=(['"])(.*?)\1/i,RE_SCRIPT_CHARSET=/\scharset=(['"])(.*?)\1/i;re_script.lastIndex=0;while((match=re_script.exec(html))){attrs=match[1];srcMatch=attrs?attrs.match(RE_SCRIPT_SRC):false;if(srcMatch&&srcMatch[2]){s=document.createElement('script');s.src=srcMatch[2];if((charsetMatch=attrs.match(RE_SCRIPT_CHARSET))&&charsetMatch[2]){s.charset=charsetMatch[2];}
s.async=true;hd.appendChild(s);}
else if((text=match[2])&&text.length>0){self._globalEval(text);}}},isDaily:function(){var self=this;if(/daily\.taobao\.net/.test(window.location.hostname)){return true;}else{return false;}}});},{requires:['node','sizzle','json']});